trainingInput:
#  scaleTier: BASIC
  scaleTier: CUSTOM
  masterType: c2-standard-8
  workerCount: 2
  workerType: e2-highmem-4
  region: europe-central2
  scheduling:
    maxWaitTime: 3600s
    maxRunningTime: 7200s